name: Create Release

on:
  push:
    branch:
      [ 'production' ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Pack
        uses: Sorrowfall/Resource-Packager@main
        with:
          parts:
            pack/
          name: Clovercraft Resource Pack
          output-directory: build
          optimize-jsons: true
